import { Dimensions, Platform } from 'react-native';

const device = Dimensions.get('window');
const settings = {
  // baseUrl: 'http://teamgroovy.in/pipeline/web/api/',
  // api: 'http://teamgroovy.in/pipeline/web/api/',
  // baseUrl: 'http://192.168.0.163/pipelocal/web/api/',
  // api: 'http://www.buyandsellmotorparts.com/api/',
  baseUrl: 'http://www.buyandsellmotorparts.com/',
  api: 'http://www.buyandsellmotorparts.com/',
  endpoints: {
    login: 'api/login',
    logout: 'api/logout',
    EditAd:'api/EditAd',
    forgot: 'api/userForgot',
    syncFirst: 'sync/syncall',
    sync: 'sync/save',
    getItems: 'api/items',
    watch:'api/watching',
    itemDetail:'api/ItemDetail',
    getUserOffer:'api/GetUserOffer',
    getChatUser:'api/GetChatUser',
    unhideChatUser:'api/unhideChatUser',
    getAchived:'api/GetAchived',
    storeDetail:'api/StoreDetail',
    blockuser:'api/blockuser',
    getBlockedUser: 'api/getBlockedUser',
    getFeaturedContent:'api/getFeaturedContent',
    follow: 'api/follow',
    getSellerReview: 'api/getSellerReview',
    getotheruser:'api/getotheruser',
    unblockuser: 'api/unblockuser',
    allCategory:'api/allCatrgory',
    ContactCategory:'api/ContactCategory',
    AboutPage:'api/AboutPage',
    EditStore:'api/EditStore',
    EditProfile:'api/EditProfile',
    ListUnlist: 'api/ListUnlist',
    MakeAchived: 'api/MakeAchived',
    MakeBuyAchived: 'api/MakeBuyAchived',
    sold: 'api/sold',
    adDelete: 'api/adDelete',
    watching: 'api/watching',
    MakeUnAchived: 'api/MakeUnAchived',
    BuyingUnarchived: 'api/BuyingUnarchived',
    getLatLong:'api/getLatLong',
    signup: 'api/signup',
    ChangePassword: 'api/ChangePassword',
    resend: 'api/resend',
    confirm: 'api/confirm',
    changeUserPassword: 'api/changeUserPassword',    
    showuserChat: 'api/showuserChat',
    deleteChat:'api/deleteChat',
    Address:'api/Address',
    viewChat:'api/viewChat',
    contact:'api/contact',
    setCity: 'api/setCity',
    reportcategory: 'api/reportcategory',
    report: 'api/report',
    makeOfferOrAsk: 'api/makeOfferOrAsk',
    Sendmessage: 'api/Sendmessage',
    addPost:'api/addPost',
    GetStoreName:'api/GetStoreName',
    SetUuid:'api/SetUuid',
    signup:'api/signup',
    getPageUrl: 'api/getPageUrl',
    getProcuctChatUser: 'api/GetProcuctChatUser',
    Rating: 'api/Rating',
    saverating: 'api/saverating',
    getFollowers: 'api/GetFollowers',
    itemFeatureanalytics: 'api/itemFeatureanalytics',
    Suggetions:'api/Suggetions',
    populartags:'api/populartags',
    savealert:'api/savealert',
    deletuseralert:'api/deletuseralert',
    removeallhistory:'api/removeallhistory',
    notificationlist:'api/notificationlist',
    StoreCreate: 'api/StoreCreate',
    upgradeuser:'api/upgradeuser',
    boostuserad:'api/boostuserad',
    changeChatStatus:'api/changeChatStatus',
    IncreaseAdViews: 'api/IncreaseAdViews',
    checkUserPost: 'api/checkUserPost',
    getAlertMsg: 'api/getAlertMsg',
    GetHomeData:'api/GetHomeData'
  },
  version: {
    android: '1.0.0',
    ios: '1.0.0',
  },
  devMode: __DEV__,
  paypalTest: true,
  token: null,
  homepageNoEntryToast: 'Please select location',
  borderIssue: Platform.OS === 'android' && Platform.Version < 21,
  isIphoneX: Platform.OS === 'ios' && !Platform.isPad && !Platform.isTVOS && (device.height === 812 || device.width === 812),
  maxItemsPerPage: 4,
  syncInterval: 60000,
  bannerAdId : __DEV__ ? 'ca-app-pub-3940256099942544/6300978111' : 'ca-app-pub-9293307221246890/2350856744',
  interstitial :  __DEV__ ? 'ca-app-pub-3940256099942544/5224354917' : 'ca-app-pub-9293307221246890/9068717458',
  syncTables: ['pipe', 'pipe_reception'],
  noSyncTables: ['sqlite_sequence', 'android_metadata', 'user_token', 'defact_picture', 'taxonomy'],
};
export default settings;
