import { Platform } from 'react-native';
import { FORTAB } from './MQ';
import settings from './settings';

const colors = {
  navBarBackgroundColor: '#fff',
  navBarTextColor: '#F66407',
  navBarSubtitleTextColor: '#F66407',
  navBarButtonColor: '#F66407',
  statusBarTextColorScheme: Platform.OS === 'ios' ? 'dark' : 'light',
  statusBarColor: Platform.OS === 'ios' ? '#87c930' : '#87c930',
  navBarSubtitleColor: '#F66407',
  mainGradient: {
    colors: ['#f3a00500', '#f3a00533', '#f3a00566'],
    location: [0.75, 0.85, 1],
  },

  buttonGradient: {
    colors: ['#f3a005', '#f76131'],
    location: [0.5, 0.75, 0.9],
    start: { x: 0.0, y: 0.0 },
    end: { x: 1.0, y: 0.0 },
  },
  brandBackgroundDark: '#162327',
  brandBackgroundLight: 'white',
  brandDarkOrange: '#f76131',
  brandBtnColor: '#F66407',
  tabBarBackGround: '#FFF',
  tabBarHeight: FORTAB ? 49 : 50,
  tabBarSelectedIconColor: '#f3a005',
  tabBarIconColor: '#888',
  pureWhite: '#FFFF',
  disableGrey: '#CCC',
  semiTransparentWhite: '#fff5',
  greyBtn: '#8e8e93',
  validColor: '#0F0',
  errorColor: '#F00',
  warningColor: '#A80',
  focusColor: '#000',
  unFocusColor: '#BBB',
  headerHeight: Platform.OS === 'ios' ? (settings.isIphoneX ? 32 : 22) : Platform.Version < 21 ? 0 : 0,

  fonts: {
    raleway: {
      bold: 'Raleway-Bold',
      semiBold: 'Raleway-SemiBold',
      light: 'Raleway-Light',
      regular: 'Raleway-Regular',
      black: 'Raleway-Black',
      italic: 'Raleway-Italic',
    },
    roboto: {
        bold: 'Roboto-Bold',
        light: 'Roboto-Light',
        regular: 'Roboto-Regular',
        italic: 'Roboto-Italic',
    },
    openSans: {
      bold: 'OpenSans-Bold',
      boldItalic: 'OpenSans-BoldItalic',
      extraBold: 'OpenSans-ExtraBold',
      extraBoldItalic: 'OpenSans-ExtraBoldItalic',
      italic: 'OpenSans-Italic',
      light: 'OpenSans-Light',
      lightItalic: 'OpenSans-LightItalic',
      regular: 'OpenSans-Regular',
      semiBold: 'OpenSans-SemiBold',
      semiBoldItalic: 'OpenSans-SemiBoldItalic',
    },
    montserrat: {
      black: 'Montserrat-Black',
      blackItalic: 'Montserrat-BlackItalic',
      bold: 'Montserrat-Bold',
      boldItalic: 'Montserrat-BoldItalic',
      extraBold: 'Montserrat-ExtraBold',
      extraBoldItalic: 'Montserrat-ExtraBoldItalic',
      extraLight: 'Montserrat-ExtraLight',
      extraLightItalic: 'Montserrat-ExtraLightItalic',
      italic: 'Montserrat-Italic',
      light: 'Montserrat-Light',
      lightItalic: 'Montserrat-LightItalic',
      medium: 'Montserrat-Medium',
      mediumItalic: 'Montserrat-MediumItalic',
      regular: 'Montserrat-Regular',
      semiBold: 'Montserrat-SemiBold',
      semiBoldItalic: 'Montserrat-SemiBoldItalic',
      thin: 'Montserrat-Thin',
      thinItalic: 'Montserrat-ThinItalic',
    },
  },
  navBarTextFontFamily: 'Montserrat-SemiBold',

};
export default colors;
